# Generated by Django 3.0.8 on 2020-07-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='article',
        ),
    ]
